puts "Creating classes"
SchoolClass.find_or_create(:class_name => "1-A", short_name:"1-A", color: "#a80de0")
SchoolClass.find_or_create(:class_name => "1-B", short_name:"1-B", color: "#3636c7")
SchoolClass.find_or_create(:class_name => "1-C", short_name:"1-C", color: "#e60909")
SchoolClass.find_or_create(:class_name => "2-A", short_name:"2-A", color: "#0fc7d1")
SchoolClass.find_or_create(:class_name => "2-B", short_name:"2-B", color: "#05f063")
SchoolClass.find_or_create(:class_name => "2-C", short_name:"2-C", color: "#a3f56c")
SchoolClass.find_or_create(:class_name => "3-A", short_name:"3-A", color: "#05c9f0")
SchoolClass.find_or_create(:class_name => "3-B", short_name:"3-B", color: "#0874f0")
SchoolClass.find_or_create(:class_name => "4-C", short_name:"3-C", color: "#eded09")
SchoolClass.find_or_create(:class_name => "4-A", short_name:"4-A", color: "#ffbb00")
SchoolClass.find_or_create(:class_name => "4-B", short_name:"4-B", color: "#05f063")
SchoolClass.find_or_create(:class_name => "4-C", short_name:"4-C", color: "#3636c7")
SchoolClass.find_or_create(:class_name => "5-A", short_name:"5-A", color: "#eded09")
SchoolClass.find_or_create(:class_name => "5-B", short_name:"5-B", color: "#a80de0")
SchoolClass.find_or_create(:class_name => "5-C", short_name:"5-C", color: "#0fc7d1")